### ISSUE TITLE
libs.versions.toml still uses loader 0.16.1

### ISSUE THREAD

**Issue by Oliver-makes-code** [QuiltMC/quilt-example-mod#10]
The libs.versions.toml still uses loader 0.16.1, while in the qmj it requires 0.17.0

**Comment by EnnuiL** [comment]
I held back bumping the version to 0.17.0 since I thought that it was still an indev release, with a VSCode issue found on QTM testing leading to me reverting to 0.16.1; I'll bump it back soon

**Comment by EnnuiL** [comment]
wait, I just realized that I forgot about QMJ; oh well
