### ISSUE TITLE
Example does not include minecraft and api info

### ISSUE THREAD

**Issue by Danjhop4** [QuiltMC/quilt-example-mod#16]
If you use the template it does not show you how to change what version you want for api or minecraft

**Comment by Oliver-makes-code** [comment]
> `// All the dependencies are declared at gradle/libs.version.toml and referenced with "libs.<id>"`

Found [here](https://github.com/QuiltMC/quilt-template-mod/blob/1.19/build.gradle#L18)

**Comment by Danjhop4** [comment]
That’s missing and build.gradle  calls a second file

**Comment by Danjhop4** [comment]
Gradle.properties that missing that info fabric does but no working examples

**Comment by oliviathevampire** [comment]
@Danjhop4 check gradle/libs.versions.toml. Quilt uses a bit more modern way to do versioning than what fabric uses.
