### ISSUE TITLE
Default to not strip trailing whitespace in markdown files

### ISSUE THREAD

**Issue by LostLuma** [QuiltMC/quilt-example-mod#24]
(GitHub?) markdown allows putting two trailing spaces before a newline to add a visible newline within markdown files. As a user it was very confusing having my editor remove them as I did not create the `.editorconfig` file or think to look there right away to spot the `trim_trailing_whitespace` rule being applied to all files.

I think for actual code files this rule makes sense to keep though.

**Comment by KiriCattus** [comment]
This doesn't just apply to Github but also Modrinth and the built in preview windows in IntelliJ (and probably others)
