### ISSUE TITLE
Add Online Mod Project Template Generator

### ISSUE THREAD

**Issue by Jaffe2718** [QuiltMC/quilt-example-mod#30]
Since it is too tedious to clone this `quilt-template-mod` and then manually modify the Mod_ID and Gradle configuration of the project. I hope QuiltMC official can release an online mod project generator with pre-set ArtifactID and Maven Group, as well as the name, description, Minecraft version, QSL version, etc. of the mod. It's similar to the FabricMC community's [template mod generator](https://fabricmc.net/develop/template/).

**Comment by OroArmor** [comment]
Yes! This is a great idea! I don't think we have the current infrastructure for it, but it is something I want to eventually explore.

Something that would be nice is if Github allowed templates to have parameters in repositories like this.

**Comment by Jaffe2718** [comment]
Using GitHub repository templates doesn't seem to work, as there is no support for modifying package names online based on developer needs. Generating project templates online and making them available for zip download would probably have to rely on a backend server, and of course renting a server would certainly be a huge overhead, which doesn't make sense. I'm not sure about the fabric community if they rent servers for this feature. It might be possible to utilize GitHub Action to run the backend server functionality instead of renting a server, I think you could try that.

**Comment by Jaffe2718** [comment]
I tried to use a pure front-end (HTML5+CSS3+JavaScript) to create this online Quilt mod project generator tool, which theoretically customizes the package name according to the user's needs and supports zip downloads. The tool is packaged zip using [JSZip](https://stuk.github.io/jszip/), a third party library.
[Tool](https://jaffe2718.github.io/quilt-template-mod-generator/)
[Source code](https://github.com/Jaffe2718/quilt-template-mod-generator)

**Comment by eristhea** [comment]
@Jaffe2718 are you aware that the version dropdowns in your tool don't work? nice project though!

**Comment by Jaffe2718** [comment]
@ix0rai 
This is because the tool's version information for both Gradle and dependent libraries is crawled in real time from the official website or Maven repository. The theory is that your poor internet connection is causing a timeout on accessing the Gradle website or Maven repository.
And not all Minecraft versions have corresponding QFAPI and QSL, so some versions don't show QFAPI and QSL versions.
![img](https://github.com/QuiltMC/quilt-template-mod/assets/114588637/2d689e8d-2879-4164-978b-77854148d8d6)

**Comment by Jaffe2718** [comment]
> I tried to use a pure front-end (HTML5+CSS3+JavaScript) to create this online Quilt module project generator tool, which theoretically customizes the package name according to the user's needs and supports zip downloads. The tool is packaged zip using [JSZip](https://stuk.github.io/jszip/), a third party library. [Tool](https://jaffe2718.github.io/quilt-template-mod-generator/) [Source code](https://github.com/Jaffe2718/quilt-template-mod-generator)

As of now, it seems that there is no way for me to add open source license generation functionality to this tool, as I didn't find any API for it.

**Comment by eristhea** [comment]
@Jaffe2718 I think this output in the firefox console has more to do with it than my connection:
![image](https://github.com/QuiltMC/quilt-template-mod/assets/66223394/047a426a-2b4d-48a5-b143-c548e5209e34)

the only extension I have which could be blocking the request is UBlock Origin

**Comment by Jaffe2718** [comment]
@ix0rai 
You can try to visit https://services.gradle.org/versions/all to test if your network can connect to gradle official version list.

**Comment by Jaffe2718** [comment]
@ix0rai 

I figured out why Firefox doesn't work properly with this tool:
1. Higher versions of Firefox block cross-origin requests by default, unless `Access-Control-Allow-Origin` is set in the response header of the target source; 
2. `https://services.gradle.org` does not set `Access-Control-Allow-Origin`, so it will be blocked by Firefox by default.

To solve this problem, there are two options below:
1. Configure the browser:
     - In the address bar of the Firefox browser type: `about:config`;
     - Set `privacy.file_unique_origin` and `security.fileuri.strict_origin_policy` to `false`;
     - Restart your browser.
3. Use a browser based on the Chromium kernel, such as `Microsoft Edge`, `Chrome`, `Arc`.

**Comment by kb-1000** [comment]
That's a bad workaround at best (and likely doesn't even work - note how these configs say file URIs), and hardly firefox' fault for implementing it better. If anything, a solution would be either a) getting gradle to change that or b) proxying the request.

**Comment by Jaffe2718** [comment]
> That's a bad workaround at best (and likely doesn't even work - note how these configs say file URIs), and hardly firefox' fault for implementing it better. If anything, a solution would be either a) getting gradle to change that or b) proxying the request.

Disabling cross-origin requests is the default security policy in higher versions of Firefox, although it is sometimes inconvenient for web developers. This tool I made mainly for chromium kernel browsers because of the large chromium user base. Of course, if you need to support Firefox, you just need to find a suitable API to get the version list of gradle, but I didn't find such an API at the moment, until then, maybe this tool is not suitable for users whose browsers disable cross-origin requests by default.

**Comment by Jaffe2718** [comment]
Of course, my tool is only an example of a tool for testing, and there are a lot of restrictions on its use, and I won't necessarily continue to maintain it afterwards. However, as far as I know, there are two ways to create GitHub Pages, branch-based and GitHub Actions-based (no need to rent a server to realize the back-end), the latter can be used as a back-end server with certain functions, theoretically, Java can be used as the back-end for version information crawling and zip production, and then the front-end is responsible for interacting with the user. In this way the acquisition of version information is done in the backend and will not be limited to the user's browser type. But this project is a lot of work, plus my personal understanding of the structure of the quilt mod project is limited, so I still hope that in the end quilt mc official can produce such a tool, using GitHub Actions to create GitHub Pages should be the optimal solution.

**Comment by lukebemish** [comment]
Yeah that's a bit silly. CORS policy stuff isn't something to just ignore or work around; it exists for a reason, and you should expect more browsers to pick up on it over time. The proper solution here is for quilt to provide an API or add something to meta for the information it needs from an external source.

**Comment by anonymous123-code** [comment]
Isnt the only issue with CORS the gradle API? What if we just hardcode that version?

**Comment by lukebemish** [comment]
Honestly a "version of gradle supported by given quilt-loom version" isn't a bad idea for something to add to meta

**Comment by anonymous123-code** [comment]
It breals at a lot more places, but I think there is a not so hacky workaround for most stuff. (Remove the QSL version handling and use mr API for QFAPI, make gradle version selection hardcoded (It would be nice if wrapper was included anyways) or use an action to update it, and use quilt meta for the rest)

**Comment by lukebemish** [comment]
Anything needed from the quilt maven can be handled by having the quilt maven provide the relevant CORS headers. Quilt meta should already be fine. The gradle one is the only URL I can see there that would pose an actual issue

**Comment by eristhea** [comment]
@Jaffe2718 asked my web friend about this, and it turns out that gradle's CORS configuration doesn't allow explicitly setting the user agent like you have in your code, and chromium browsers mishandle the rules a bit. that should be a simple fix.

**Comment by Jaffe2718** [comment]
So I think the best solution is to create GitHub Pages based on GitHub Actions, where the crawling of version information and generation of zip archives is done on the backend, and the frontend is only responsible for interacting with users. This way, you don't need to consider the user's browser type.

Even Quilt MC's officially adopted tool `https://lambdaurora.dev/tools/import_quilt.html` can't be used in Firefox because of CORS issues.

**Comment by eristhea** [comment]
?

https://lambdaurora.dev/tools/import_quilt.html works fine for me on my desktop firefox?

**Comment by Jaffe2718** [comment]
![Firefox Dev](https://github.com/QuiltMC/quilt-template-mod/assets/114588637/08b2066e-15e8-49e8-aaa2-b4f6728df5dc)

My Firefox browser is developer edition, this tool https://lambdaurora.dev/tools/import_quilt.html cannot work.

**Comment by Jaffe2718** [comment]
So in order to adapt to all users' browsers, I don't think we can start by solving the problem of browser CORS policies. The best solution is obviously to implement and deploy the backend using Java Spring and GitHub Actions.

**Comment by Jaffe2718** [comment]
I already know how fabric mc online mod project generation tool works by analyzing fabric mc's web repository https://github.com/FabricMC/fabricmc.net . They specialize in deploying no backend, also GitHub Pages. the packaging zip is the JSZip library, as for the gradle it has gradle-wrapper.properties and gradle-wrapper.jar as static resource files, and you can't choose the gradle version when packaging, but it's mandatory to use the one provided by his gradle.

**Comment by Pyrofab** [comment]
Couldn't we just add a proxy route to the gradle API through cloudflare ?

**Comment by kb-1000** [comment]
Or you could try kindly asking Gradle first :)
I mean, that API doesn't exactly have any uses within Gradle, only by third-party software like this, so they shouldn't be opposed to that

**Comment by Jaffe2718** [comment]
Perhaps Firefox users should try using a plugin first to avoid the CORS issue, after all, there isn't any currently available API to get Gradle information either.

**Comment by lukebemish** [comment]
The behavior on Firefox is the _correct_ behavior. Bypassing it or working around intended behavior, when actually using CORS is the proper solution, is absurd

**Comment by Jaffe2718** [comment]
When I switch to a stable version of Firefox, even this tool https://lambdaurora.dev/tools/import_quilt.html may not be able to use.😓
My Firefox version is 118.0.1.8670

![ff](https://github.com/QuiltMC/quilt-template-mod/assets/114588637/cb58e79a-2413-48fe-9f38-c06abcbc3e26)

At present, I do not have a way to compatible with Firefox browser, can only temporarily do not use a high version of Firefox, can temporarily use chromium kernel browser instead.

**Comment by lukebemish** [comment]
Once again, the solution is either to proxy the stuff properly to obey CORS stuff, or to ask gradle to return the proper CORS header from their API.

**Comment by Jaffe2718** [comment]
> Once again, the solution is either to proxy the stuff properly to obey CORS stuff, or to ask gradle to return the proper CORS header from their API.

It's not clear to me at the moment in which project Gradle officially maintains `services.gradle.org`, so it's not clear to me at the moment how to contact them and report this issue. If possible, you can find a way to contact Grade and report the problem.

**Comment by Jaffe2718** [comment]
It seems like the CORS issue has now been solved by removing User-Agent.
[pull 1](https://github.com/Jaffe2718/quilt-template-mod-generator/pull/1)
[Tool](https://jaffe2718.github.io/quilt-template-mod-generator/)

**Comment by LambdAurora** [comment]
> When I switch to a stable version of Firefox, even this tool https://lambdaurora.dev/tools/import_quilt.html may not be able to use.😓 My Firefox version is 118.0.1.8670
> 
> ![ff](https://user-images.githubusercontent.com/114588637/273854140-cb58e79a-2413-48fe-9f38-c06abcbc3e26.png)
> 
> At present, I do not have a way to compatible with Firefox browser, can only temporarily do not use a high version of Firefox, can temporarily use chromium kernel browser instead.

This is weird, I have never seen such issues *while being a Firefox user*.

**Comment by sylv256** [comment]
> When I switch to a stable version of Firefox, even this tool https://lambdaurora.dev/tools/import_quilt.html may not be able to use.😓 My Firefox version is 118.0.1.8670
> 
> ![ff](https://user-images.githubusercontent.com/114588637/273854140-cb58e79a-2413-48fe-9f38-c06abcbc3e26.png)
> 
> At present, I do not have a way to compatible with Firefox browser, can only temporarily do not use a high version of Firefox, can temporarily use chromium kernel browser instead.

I'm on 118.0.2, and I am not getting this. Your Firefox instance is bugged.
