### ISSUE TITLE
Unable to launch game after following example mod setup

### ISSUE THREAD

**Issue by TelepathicGrunt** [QuiltMC/quilt-example-mod#4]
I am trying to port my Fabric mod to Quilt and followed the example mod as close as I can. However, when I run the game, I am greeted with this screen.
![image](https://user-images.githubusercontent.com/40846040/164343177-0bb92b63-cafc-4cec-8262-28972bd21c3e.png)

Console output: https://paste.ee/p/AA9Jq

My mod's source: https://github.com/TelepathicGrunt/FeatureNBTDeadlockBeGone/tree/Quilt-1.18

deps:
- minecraft = "1.18.2"
- quilt_mappings = "1.18.2+build.22"
- quilt_loader = "0.16.0-beta.7"
- quilted_fabric_api = "1.0.0-beta.6+0.51.1-1.18.2"

lmk if you need more info.

**Comment by triphora** [comment]
You need to have both QSL and QFAPI.

**Comment by TelepathicGrunt** [comment]
Implemented this recent change to the example mod into my mod and game now can launch
https://github.com/QuiltMC/quilt-example-mod/commit/b2fb439e6d79f42184196f549d11a36466e3758f
