### ISSUE TITLE
Broken libs.versions.toml 

### ISSUE THREAD

**Issue by maloryware** [QuiltMC/quilt-example-mod#40]
`libs.versions.toml` calls for `quilt_standard_libraries = { module = "org.quiltmc:qsl", version.ref = "quilt_standard_libraries" }`, which has no version reference
Despite that, when attempting to assign it a version reference, building fails. Manually fixed by removing all mentions of `quilt_standard_libraries` from the bundles
![image](https://github.com/user-attachments/assets/807b8dc1-989d-466b-aed9-910ce95426ad)
Left is current, right is manually edited

**Comment by OroArmor** [comment]
was this from the template or the generator?

**Comment by eristhea** [comment]
@OroArmor has to be generator, i didn't release a broken template
