### ISSUE TITLE
Branch 1.19 refers to 1.18.2 in gradle/libs.versions.toml

### ISSUE THREAD

**Issue by lospejos** [QuiltMC/quilt-example-mod#9]
File `libs.versions.toml` in `1.19` branch
 
https://github.com/QuiltMC/quilt-template-mod/blob/1.19/gradle/libs.versions.toml

refers to `1.18.2` dependencies in `[versions]` section. Please fix.

**Comment by violet-sh** [comment]
Yep, this has now been fixed.
